### PR TITLE
Rename files. #16

### PR DESCRIPTION
**Pull request by anniekang**
Renamed stylesheet.css to default.css

### CODE REVIEW

**Comment by ronperris** [comment]
Looks like you have merge conflicts, so this can't be merged. You might have done the renaming in a branch that wasn't up to date with the current version of master.

**Comment by anniekang** [comment]
Forgot to git pull after last merge.  All updated now.  Is there still a conflict?

**Comment by ronperris** [comment]
Yes, there are still conflicts. Notice the text on the pull request page that says, "This branch has conflicts that must be resolved".

**Comment by anniekang** [comment]
When I was trying to push this branch, it was telling me that the name of this project had changed.  Changing the origin URL seemed to resolve the issue

**Pull request merged**
